services: 
  mongo_db_pastelaria-pdv:
    container_name: mongo_db_pastelaria-pdv
    image: mongo:${VERSAO_MONGO}
    ports:
      - "27017:27017"
    volumes:
      - pastelaria_data:/data/db
    restart: always
    networks:
      - net-pastelaria-pdv
  

  api-pastelaria-pdv:
    container_name: api-pastelaria-pdv
    build: .
    image: api-pastelaria:${VERSAO_APP}
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo_db_pastelaria-pdv
    restart: always
    networks:
      - net-pastelaria-pdv

volumes:
  pastelaria_data:

networks:
  net-pastelaria-pdv: