services: 
  mongo_db_pastelaria-pdv:
    container_name: mongo_db_pastelaria-pdv
    image: mongo:${VERSAO_MONGO}
    ports:
      - "27017:27017"
    volumes:
      - pastelaria_data:/data/db
    restart: always
    networks:
      - net-pastelaria-pdv
  

  api-pastelaria-pdv:
    container_name: api-pastelaria-pdv
    build:
      context: ${DIR_DOCKERFILE_API}
    image: api-pastelaria:${VERSAO_APP}
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo_db_pastelaria-pdv
    restart: always
    networks:
      - net-pastelaria-pdv


  frontend-pastelaria-pdv:
    container_name: frontend-pastelaria-pdv
    build:
      context: ${DIR_DOCKERFILE_FRONTEND}
    image: frontend-pastelaria:${VERSAO_FRONTEND}
    ports:
      - "8080:80"
    depends_on:
      - api-pastelaria-pdv
    networks:
      - net-pastelaria-pdv

volumes:
  pastelaria_data:

networks:
  net-pastelaria-pdv:
