services: 
<<<<<<< HEAD
  mongo_db_pastelaria:
    image: mongo:latest
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
=======
  mongo_db_pastelaria-pdv:
    container_name: mongo_db_pastelaria-pdv
    image: mongo:${VERSAO_MONGO}
>>>>>>> a4f6597 (ref: refatorando image dockerfile de api e docker compose removendo mongo replica)
    ports:
      - "27017:27017"
    volumes:
      - pastelaria_data:/data/db
      - ./docker/mongo-init-replica.js:/docker-entrypoint-initdb.d/mongo-init-replica.js:ro
    restart: always
    networks:
      - net-pastelaria-pdv
  
<<<<<<< HEAD
  api-pastelaria:
    container_name: api-pastelaria
=======

  api-pastelaria-pdv:
    container_name: api-pastelaria-pdv
>>>>>>> a4f6597 (ref: refatorando image dockerfile de api e docker compose removendo mongo replica)
    build: .
    image: api-pastelaria:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo_db_pastelaria:27017/pastelaria?replicaSet=rs0
    depends_on:
      - mongo_db_pastelaria-pdv
    restart: always
    networks:
      - net-pastelaria-pdv

volumes:
  pastelaria_data:

networks:
  net-pastelaria-pdv: