services: 
  api-pastelaria-pdv:
    container_name: api-pastelaria-pdv
    image: api-pastelaria:${VERSAO_APP}
    restart: always
    ports:
      - "5000:5000"
    networks:
      - net-pdv
    environment:
      - MONGO_URI=${MONGO_URI_PRD}

  frontend-pastelaria-pdv:
    container_name: frontend-pastelaria-pdv
    image: frontend-pastelaria:${VERSAO_FRONTEND}
    restart: always
    ports:
      - "8080:80"
    networks:
      - net-pdv
    depends_on:
        - api-pastelaria-pdv

networks:
  net-pdv:
    driver: bridge
